[bar.plugins.imgur]
api_key = ""

[bar.plugins.youtube]
api_key = ""

[bar.plugins.vimeo]
api_key = ""

[bar.network]
name = "bar"
enable = true

[bar.features]
report_metadata = false
report_mime = false
mask_highlights = false
send_notice = false
history = false
cross_channel_history = false
invite = false
autosave = false
send_errors_to_poster = false
reply_with_errors = false
partial_urls = false
nick_response = false
reconnect = false

[bar.parameters]
url_limit = 10
status_channels = []
nick_response_str = ""
reconnect_timeout = 10

[bar.http]
timeout_s = 10
max_redirections = 10
max_retries = 3
retry_delay_s = 5
accept_lang = "en"

[bar.database]
type = "in-memory"

[bar.connection]
nickname = "url-bot-rs"
nick_password = ""
alt_nicks = ["url-bot-rs_"]
username = "url-bot-rs"
realname = "url-bot-rs"
server = "127.0.0.1"
port = 6667
password = ""
use_ssl = false
channels = ["#url-bot-rs"]
user_info = "Feed me URLs."
[foo.plugins.imgur]
api_key = ""

[foo.plugins.youtube]
api_key = ""

[foo.plugins.vimeo]
api_key = ""

[foo.network]
name = "foo"
enable = true

[foo.features]
report_metadata = false
report_mime = false
mask_highlights = false
send_notice = false
history = false
cross_channel_history = false
invite = false
autosave = false
send_errors_to_poster = false
reply_with_errors = false
partial_urls = false
nick_response = false
reconnect = false

[foo.parameters]
url_limit = 10
status_channels = []
nick_response_str = ""
reconnect_timeout = 10

[foo.http]
timeout_s = 10
max_redirections = 10
max_retries = 3
retry_delay_s = 5
accept_lang = "en"

[foo.database]
type = "in-memory"

[foo.connection]
nickname = "url-bot-rs"
nick_password = ""
alt_nicks = ["url-bot-rs_"]
username = "url-bot-rs"
realname = "url-bot-rs"
server = "127.0.0.1"
port = 6667
password = ""
use_ssl = false
channels = ["#url-bot-rs"]
user_info = "Feed me URLs."
