.TH URL-BOT-RS 1
.SH NAME
url\-bot\-rs \- Standalone IRC bot; for resolving URLs posted, retrieving, and posting page titles to a configurable IRC server and channels
.SH SYNOPSIS
\fBurl\-bot\-rs\fR [FLAGS] [OPTIONS]
.SH FLAGS
.TP
\fB\-\-version\fR
Print version information.

.TP
\fB\-\-help\fR
Show usage.

.TP
\fB\-v\fR, \fB\-\-verbose\fR
Enable verbose mode. Add extra \-v flags for increased verbosity, and printing of debugging information. For example, this can include information pertaining to website retrieval and title parsing, or printing of all received irc messages.

.TP
\fB\-t\fR, \fB\-\-timestamp\fR
Force timestamps in the output, even if they have been automatically disabled.
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-db\fR=\fIdatabase\fR
Path to store a sqlite database. If not provided, a default path is used, based on the XDG specification.

.TP
\fB\-c\fR, \fB\-\-conf\fR=\fIconfiguration\fR
Path to read configuration file from. If not provided, a default path is used, based on the XDG specification.
.SH CONFIGURATION
Most settings are read from the configuration file. This includes the details used to connect to an IRC server, features, and some runtime parameters. Running for the first time, a default\-valued configuration will be generated in either the default XDG config path, or in the location specified with \-\-conf. Once the bot has been run for the first time, and the default configuration has been generated, this should be edited and the bot restarted.


.SH EXIT STATUS
.TP
\fB0\fR
Successful program execution.

.TP
\fB1\fR
Unsuccessful program execution.

.TP
\fB101\fR
The program panicked.
.SH AUTHOR
.P
.RS 2
.nf
Ed Cragg <drq.11325@gmail.com>
